/*
 * File: app/store/landinfo1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.landinfo1', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.lyjMyData'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'MyApp.model.lyjMyData',
            storeId: 'landinfo1',
            pageSize: 10,
            proxy: {
                type: 'ajax',
                url: 'http://localhost:8080/lyj0816/find_transinfo',
                reader: {
                    type: 'json',
                    root: 'root'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onJsonstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {
        var extra_params={outArea:Ext.getCmp('areaID').getValue(),
                outAcre:Ext.getCmp('acreID').getValue(),
                outTranstyle:Ext.getCmp('transtyleID').getValue(),
            outYear:Ext.getCmp('yearID').getValue()};
        Ext.apply(store.proxy.extraParams,extra_params);
    }

});