/*
 * File: app/store/transtyleStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.transtyleStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'transtyleStore',
            data: [
                [
                    '租赁',
                    '租赁'
                ],
                [
                    '转包',
                    '转包'
                ],
                [
                    '合作',
                    '合作'
                ],
                [
                    '转让',
                    '转让'
                ],
                [
                    '互换',
                    '互换'
                ],
                [
                    '入股',
                    '入股'
                ],
                [
                    '求租',
                    '求租'
                ],
                [
                    '求购',
                    '求购'
                ],
                [
                    '招拍挂',
                    '招拍挂'
                ]
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'style'
                },
                {
                    name: 'styleText'
                }
            ]
        }, cfg)]);
    }
});