package cn.edu.bnu.land.model;

// Generated 2014-3-26 15:08:03 by Hibernate Tools 4.0.0

/**
 * BenefitCanshutai generated by hbm2java
 */
public class BenefitCanshutai implements java.io.Serializable {

	private int ffcs;
	private Integer zgjg;
	private Integer zdjg;
	private Integer zdcjl;
	private Integer xyz;
	private Integer jb;

	public BenefitCanshutai() {
	}

	public BenefitCanshutai(int ffcs) {
		this.ffcs = ffcs;
	}

	public BenefitCanshutai(int ffcs, Integer zgjg, Integer zdjg,
			Integer zdcjl, Integer xyz, Integer jb) {
		this.ffcs = ffcs;
		this.zgjg = zgjg;
		this.zdjg = zdjg;
		this.zdcjl = zdcjl;
		this.xyz = xyz;
		this.jb = jb;
	}

	public int getFfcs() {
		return this.ffcs;
	}

	public void setFfcs(int ffcs) {
		this.ffcs = ffcs;
	}

	public Integer getZgjg() {
		return this.zgjg;
	}

	public void setZgjg(Integer zgjg) {
		this.zgjg = zgjg;
	}

	public Integer getZdjg() {
		return this.zdjg;
	}

	public void setZdjg(Integer zdjg) {
		this.zdjg = zdjg;
	}

	public Integer getZdcjl() {
		return this.zdcjl;
	}

	public void setZdcjl(Integer zdcjl) {
		this.zdcjl = zdcjl;
	}

	public Integer getXyz() {
		return this.xyz;
	}

	public void setXyz(Integer xyz) {
		this.xyz = xyz;
	}

	public Integer getJb() {
		return this.jb;
	}

	public void setJb(Integer jb) {
		this.jb = jb;
	}

}
