package cn.edu.bnu.land.model;

// Generated 2013-10-5 11:38:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PublicProject generated by hbm2java
 */
public class PublicProject implements java.io.Serializable {

	private Integer projectId;
	private String projectname;
	private String rlocation;
	private String rmapnumber;
	private String rarea;
	private String rproperty;
	private String rqualityFlag;
	private String conUnit;
	private Date starttime;
	private Date completiontime;
	private String rmoney;

	public PublicProject() {
	}

	public PublicProject(String projectname, String rlocation,
			String rmapnumber, String rarea, String rproperty,
			String rqualityFlag, String conUnit, Date starttime,
			Date completiontime, String rmoney) {
		this.projectname = projectname;
		this.rlocation = rlocation;
		this.rmapnumber = rmapnumber;
		this.rarea = rarea;
		this.rproperty = rproperty;
		this.rqualityFlag = rqualityFlag;
		this.conUnit = conUnit;
		this.starttime = starttime;
		this.completiontime = completiontime;
		this.rmoney = rmoney;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public String getProjectname() {
		return this.projectname;
	}

	public void setProjectname(String projectname) {
		this.projectname = projectname;
	}

	public String getRlocation() {
		return this.rlocation;
	}

	public void setRlocation(String rlocation) {
		this.rlocation = rlocation;
	}

	public String getRmapnumber() {
		return this.rmapnumber;
	}

	public void setRmapnumber(String rmapnumber) {
		this.rmapnumber = rmapnumber;
	}

	public String getRarea() {
		return this.rarea;
	}

	public void setRarea(String rarea) {
		this.rarea = rarea;
	}

	public String getRproperty() {
		return this.rproperty;
	}

	public void setRproperty(String rproperty) {
		this.rproperty = rproperty;
	}

	public String getRqualityFlag() {
		return this.rqualityFlag;
	}

	public void setRqualityFlag(String rqualityFlag) {
		this.rqualityFlag = rqualityFlag;
	}

	public String getConUnit() {
		return this.conUnit;
	}

	public void setConUnit(String conUnit) {
		this.conUnit = conUnit;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getCompletiontime() {
		return this.completiontime;
	}

	public void setCompletiontime(Date completiontime) {
		this.completiontime = completiontime;
	}

	public String getRmoney() {
		return this.rmoney;
	}

	public void setRmoney(String rmoney) {
		this.rmoney = rmoney;
	}

}
