package cn.edu.bnu.land.model;

// Generated 2013-8-16 10:11:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Transinfo generated by hbm2java
 */
public class Transinfo implements java.io.Serializable {

	private Integer landid;
	private String area;
	private Integer acre;
	private String transtyle;
	private Integer year;
	private Float price;
	private Date releasedate;
	private String trading;

	public Transinfo() {
	}

	public Transinfo(String area, Integer acre, String transtyle, Integer year,
			Float price, Date releasedate,String trading) {
		this.area = area;
		this.acre = acre;
		this.transtyle = transtyle;
		this.year = year;
		this.price = price;
		this.releasedate = releasedate;
		this.trading = trading;
	}

	public Integer getLandid() {
		return this.landid;
	}

	public void setLandid(Integer landid) {
		this.landid = landid;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Integer getAcre() {
		return this.acre;
	}

	public void setAcre(Integer acre) {
		this.acre = acre;
	}

	public String getTranstyle() {
		return this.transtyle;
	}

	public void setTranstyle(String transtyle) {
		this.transtyle = transtyle;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Date getReleasedate() {
		return this.releasedate;
	}

	public void setReleasedate(Date releasedate) {
		this.releasedate = releasedate;
	}

	public String getTrading() {
		return trading;
	}

	public void setTrading(String trading) {
		this.trading = trading;
	}

}
