package cn.edu.bnu.land.model;

// Generated 2014-3-12 10:33:29 by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.stereotype.Repository;

/**
 * Zcwhistoryofdeposit generated by hbm2java
 */
@Repository
public class Zcwhistoryofdeposit implements java.io.Serializable {

	private Integer id;
	private String loginname;
	private String realname;
	private String ticketid;
	private Date operatedate;
	private String comein;
	private String getout;
	private String yue;
	private String operator;

	public Zcwhistoryofdeposit() {
	}

	public Zcwhistoryofdeposit(String loginname, String realname,
			String ticketid, Date operatedate, String comein, String getout,
			String yue, String operator) {
		this.loginname = loginname;
		this.realname = realname;
		this.ticketid = ticketid;
		this.operatedate = operatedate;
		this.comein = comein;
		this.getout = getout;
		this.yue = yue;
		this.operator = operator;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getTicketid() {
		return this.ticketid;
	}

	public void setTicketid(String ticketid) {
		this.ticketid = ticketid;
	}

	public Date getOperatedate() {
		return this.operatedate;
	}

	public void setOperatedate(Date operatedate) {
		this.operatedate = operatedate;
	}

	public String getComein() {
		return this.comein;
	}

	public void setComein(String comein) {
		this.comein = comein;
	}

	public String getGetout() {
		return this.getout;
	}

	public void setGetout(String getout) {
		this.getout = getout;
	}

	public String getYue() {
		return this.yue;
	}

	public void setYue(String yue) {
		this.yue = yue;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
