package cn.edu.bnu.land.model;

// Generated 2014-3-12 7:26:17 by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.stereotype.Repository;

/**
 * ZcwMangementOfDeposit generated by hbm2java
 */
@Repository
public class ZcwMangementOfDeposit implements java.io.Serializable {

	private Integer id;
	private String loginName;
	private String ticketId;
	private String deposit;
	private String statusofdeposit;
	private String contract;
	private String bidResult;
	private String returnstatus;
	private Date diedline;

	public ZcwMangementOfDeposit() {
	}

	public ZcwMangementOfDeposit(String loginName, String ticketId,
			String deposit, String statusofdeposit, String contract,
			String bidResult, String returnstatus, Date diedline) {
		this.loginName = loginName;
		this.ticketId = ticketId;
		this.deposit = deposit;
		this.statusofdeposit = statusofdeposit;
		this.contract = contract;
		this.bidResult = bidResult;
		this.returnstatus = returnstatus;
		this.diedline = diedline;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(String ticketId) {
		this.ticketId = ticketId;
	}

	public String getDeposit() {
		return this.deposit;
	}

	public void setDeposit(String deposit) {
		this.deposit = deposit;
	}

	public String getStatusofdeposit() {
		return this.statusofdeposit;
	}

	public void setStatusofdeposit(String statusofdeposit) {
		this.statusofdeposit = statusofdeposit;
	}

	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	public String getBidResult() {
		return this.bidResult;
	}

	public void setBidResult(String bidResult) {
		this.bidResult = bidResult;
	}

	public String getReturnstatus() {
		return this.returnstatus;
	}

	public void setReturnstatus(String returnstatus) {
		this.returnstatus = returnstatus;
	}

	public Date getDiedline() {
		return this.diedline;
	}

	public void setDiedline(Date diedline) {
		this.diedline = diedline;
	}

}
