package cn.edu.bnu.land.model;

import org.springframework.stereotype.Repository;

// Generated 2014-4-1 9:37:20 by Hibernate Tools 4.0.0

/**
 * Zcwsignandrecord generated by hbm2java
 */
@Repository
public class Zcwsignandrecord implements java.io.Serializable {

	private Integer id;
	private String loginName;
	private String ticketid;
	private String type;
	private String amount;
	private String price;
	private String totalprice;
	private String winner;
	private String windate;
	private String contractid;
	private String netsignid;
	private String contractstatus;
	private String contractcontent;
	private String paymentstatus;
	private String material;
	private String jycheck;
	private String record;
	private String certification;

	public Zcwsignandrecord() {
	}

	public Zcwsignandrecord(String loginName, String ticketid, String type,
			String amount, String price, String totalprice, String winner,
			String windate, String contractid, String netsignid,
			String contractstatus, String contractcontent,
			String paymentstatus, String material, String jycheck,
			String record, String certification) {
		this.loginName = loginName;
		this.ticketid = ticketid;
		this.type = type;
		this.amount = amount;
		this.price = price;
		this.totalprice = totalprice;
		this.winner = winner;
		this.windate = windate;
		this.contractid = contractid;
		this.netsignid = netsignid;
		this.contractstatus = contractstatus;
		this.contractcontent = contractcontent;
		this.paymentstatus = paymentstatus;
		this.material = material;
		this.jycheck = jycheck;
		this.record = record;
		this.certification = certification;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getTicketid() {
		return this.ticketid;
	}

	public void setTicketid(String ticketid) {
		this.ticketid = ticketid;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(String totalprice) {
		this.totalprice = totalprice;
	}

	public String getWinner() {
		return this.winner;
	}

	public void setWinner(String winner) {
		this.winner = winner;
	}

	public String getWindate() {
		return this.windate;
	}

	public void setWindate(String windate) {
		this.windate = windate;
	}

	public String getContractid() {
		return this.contractid;
	}

	public void setContractid(String contractid) {
		this.contractid = contractid;
	}

	public String getNetsignid() {
		return this.netsignid;
	}

	public void setNetsignid(String netsignid) {
		this.netsignid = netsignid;
	}

	public String getContractstatus() {
		return this.contractstatus;
	}

	public void setContractstatus(String contractstatus) {
		this.contractstatus = contractstatus;
	}

	public String getContractcontent() {
		return this.contractcontent;
	}

	public void setContractcontent(String contractcontent) {
		this.contractcontent = contractcontent;
	}

	public String getPaymentstatus() {
		return this.paymentstatus;
	}

	public void setPaymentstatus(String paymentstatus) {
		this.paymentstatus = paymentstatus;
	}

	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	public String getJycheck() {
		return this.jycheck;
	}

	public void setJycheck(String jycheck) {
		this.jycheck = jycheck;
	}

	public String getRecord() {
		return this.record;
	}

	public void setRecord(String record) {
		this.record = record;
	}

	public String getCertification() {
		return this.certification;
	}

	public void setCertification(String certification) {
		this.certification = certification;
	}

}
