package cn.edu.bnu.land.model;

// Generated 2014-3-19 10:10:31 by Hibernate Tools 4.0.0

import java.util.Date;

import org.springframework.stereotype.Repository;

/**
 * ZcwTicketManagement generated by hbm2java
 */
@Repository
public class ZcwTicketManagement implements java.io.Serializable {

	private Integer id;
	private String inorout;
	private String amount;
	private String reclamationid;
	private String lotid;
	private String seller;
	private String proxy;
	private String statu;
	private String explain;
	private Date date;
	private String overage;

	public ZcwTicketManagement() {
	}

	public ZcwTicketManagement(String inorout, String amount, Date date,
			String overage) {
		this.inorout = inorout;
		this.amount = amount;
		this.date = date;
		this.overage = overage;
	}

	public ZcwTicketManagement(String inorout, String amount,
			String reclamationid, String lotid, String seller, String proxy,
			String statu, String explain, Date date, String overage) {
		this.inorout = inorout;
		this.amount = amount;
		this.reclamationid = reclamationid;
		this.lotid = lotid;
		this.seller = seller;
		this.proxy = proxy;
		this.statu = statu;
		this.explain = explain;
		this.date = date;
		this.overage = overage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getInorout() {
		return this.inorout;
	}

	public void setInorout(String inorout) {
		this.inorout = inorout;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public String getReclamationid() {
		return this.reclamationid;
	}

	public void setReclamationid(String reclamationid) {
		this.reclamationid = reclamationid;
	}

	public String getLotid() {
		return this.lotid;
	}

	public void setLotid(String lotid) {
		this.lotid = lotid;
	}

	public String getSeller() {
		return this.seller;
	}

	public void setSeller(String seller) {
		this.seller = seller;
	}

	public String getProxy() {
		return this.proxy;
	}

	public void setProxy(String proxy) {
		this.proxy = proxy;
	}

	public String getStatu() {
		return this.statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	public String getExplain() {
		return this.explain;
	}

	public void setExplain(String explain) {
		this.explain = explain;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getOverage() {
		return this.overage;
	}

	public void setOverage(String overage) {
		this.overage = overage;
	}

}
