package cn.edu.bnu.land.model;
// Generated 2014-3-2 15:51:45 by Hibernate Tools 4.0.0


import java.util.Date;

import org.springframework.stereotype.Repository;

/**
 * ZSellerInfo generated by hbm2java
 */
@Repository
public class ZSellerInfo  implements java.io.Serializable {


     private String loginname;
     private String password;
     private String realname;
     private String sex;
     private Date birthdate;
     private String idnum;
     private String typelx;
     private String company;
     private String telephone;
     private String phone;
     private String elemail;
     private String address;
     private String mail;
     private String fax;

    public ZSellerInfo() {
    }

	
    public ZSellerInfo(String loginname) {
        this.loginname = loginname;
    }
    public ZSellerInfo(String loginname, String password, String realname, String sex, Date birthdate, String idnum, String typelx, String company, String telephone, String phone, String elemail, String address, String mail, String fax) {
       this.loginname = loginname;
       this.password = password;
       this.realname = realname;
       this.sex = sex;
       this.birthdate = birthdate;
       this.idnum = idnum;
       this.typelx = typelx;
       this.company = company;
       this.telephone = telephone;
       this.phone = phone;
       this.elemail = elemail;
       this.address = address;
       this.mail = mail;
       this.fax = fax;
    }
   
    public String getLoginname() {
        return this.loginname;
    }
    
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRealname() {
        return this.realname;
    }
    
    public void setRealname(String realname) {
        this.realname = realname;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }
    public String getIdnum() {
        return this.idnum;
    }
    
    public void setIdnum(String idnum) {
        this.idnum = idnum;
    }
    public String getTypelx() {
        return this.typelx;
    }
    
    public void setTypelx(String typelx) {
        this.typelx = typelx;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getElemail() {
        return this.elemail;
    }
    
    public void setElemail(String elemail) {
        this.elemail = elemail;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }




}


