/*
 * File: app/view/bzjpz.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.bzjpz', {
    extend: 'Ext.window.Window',
    alias: 'widget.bzjpz',

    height: 462,
    id: 'bzjpz',
    width: 636,
    layout: {
        type: 'absolute'
    },
    title: '支付凭证',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    height: 380,
                    id: 'zfpz',
                    width: 620
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        //var w=this.getEl().findParentNode('window[id=bzjpz]');
                        //w.getEl().close();
                        //var i=Ext.query('#bzjpz');

                        //alert(i.getId());
                        //alert(this.getId());
                        //alert(this.getEl().getId());
                        var w=Ext.getCmp('bzjpz');
                        w.close();
                    },
                    x: 260,
                    y: 400,
                    width: 90,
                    text: '关闭'
                }
            ]
        });

        me.callParent(arguments);
    }

});