/*
 * File: app/view/ccQueryStatisticsTab.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ccQueryStatisticsTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ccQueryStatisticsTab',

    id: 'ccQueryStatisticsTab',
    autoScroll: true,
    layout: {
        type: 'fit'
    },
    title: '建设用地查询与统计',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: '查询',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    autoRender: false,
                                    id: 'ccQueryStatisticTable',
                                    store: 'ccQueryStatisticStore',
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: ''
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: '查询'
                                                }
                                            ]
                                        }
                                    ],
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'id',
                                            text: '编号',
                                            format: '0'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'ticketId',
                                            text: '地票',
                                            format: '0'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'isPush',
                                            text: '是否推送',
                                            falseText: '否',
                                            trueText: '是'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            dataIndex: 'publishDate',
                                            text: '发布日期'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'area',
                                            text: '地票面积（亩）'
                                        },
                                        {
                                            xtype: 'booleancolumn',
                                            dataIndex: 'isMailPush',
                                            text: '是否邮件推送',
                                            falseText: '否',
                                            trueText: '是'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'price',
                                            text: '地票价格（万）'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'auction',
                                            text: '拍卖方式'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'supplier',
                                            text: '供应方'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'region',
                                            text: '行政区'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'others',
                                            text: '其他'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'border'
                            },
                            title: '统计',
                            items: [
                                {
                                    xtype: 'panel',
                                    region: 'west',
                                    split: true,
                                    width: 150,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: '选择统计图表：',
                                    items: [
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var myTabPanel = Ext.getCmp('StatisticForm');
                                                myTabPanel.setActiveTab('StatisticForm_Bar');
                                                //var tabs = myTabPanel.getActiveTab();
                                                //myTabPanel.removeAll(true);
                                                //myTabPanel.add(tabs);
                                                //Ext.Msg.alert("",tabs.id);
                                            },
                                            flex: 1,
                                            height: 40,
                                            id: 'tjtb_supplier',
                                            maxHeight: 40,
                                            text: '地块供应方'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var myTabPanel = Ext.getCmp('StatisticForm');
                                                myTabPanel.setActiveTab('StatisticForm_Pie');
                                            },
                                            flex: 1,
                                            height: 40,
                                            id: 'tjtb_Auction',
                                            maxHeight: 40,
                                            text: '拍卖方式'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var myTabPanel = Ext.getCmp('StatisticForm');
                                                myTabPanel.setActiveTab('StatisticForm_Line');
                                            },
                                            flex: 1,
                                            height: 40,
                                            id: 'tjtb_price_time',
                                            maxHeight: 40,
                                            text: '地块价格趋势'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var myTabPanel = Ext.getCmp('StatisticForm');
                                                myTabPanel.setActiveTab('StatisticForm_Point');
                                            },
                                            flex: 1,
                                            height: 40,
                                            id: 'tjtb_area',
                                            maxHeight: 40,
                                            text: '地块面积统计'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tabpanel',
                                    flex: 1,
                                    region: 'center',
                                    id: 'StatisticForm',
                                    activeTab: 1,
                                    tabPosition: 'bottom',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            id: 'StatisticForm_Bar',
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: '柱状图',
                                            items: [
                                                {
                                                    xtype: 'image',
                                                    src: 'images/Query_Bar.jpg'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            id: 'StatisticForm_Pie',
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: '饼状图',
                                            items: [
                                                {
                                                    xtype: 'image',
                                                    src: 'images/Query_Pie.png'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            id: 'StatisticForm_Line',
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: '折线图',
                                            items: [
                                                {
                                                    xtype: 'image',
                                                    src: 'images/Query_Line.jpg'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            id: 'StatisticForm_Point',
                                            layout: {
                                                type: 'fit'
                                            },
                                            title: '散点图',
                                            items: [
                                                {
                                                    xtype: 'image',
                                                    src: 'images/Query_Bar2.jpg'
                                                }
                                            ]
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: '刷新'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: '保存'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});