/*
 * File: app/view/Crawl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Crawl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.Crawl',

    height: 459,
    width: 756,
    autoScroll: true,
    layout: {
        type: 'border'
    },
    title: '检索网站设置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'label',
                            html: '<a target="_blank" href = " http://localhost:8090/index-lyj.jsp">信息采集管理面板</a>',
                            margin: 10,
                            width: 150
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'crawlurlForm',
                    layout: {
                        type: 'fit'
                    },
                    bodyPadding: 10,
                    header: false,
                    title: '检索网站设置',
                    url: 'look_url',
                    items: [
                        {
                            xtype: 'gridpanel',
                            collapsed: false,
                            title: '现有信息来源网站列表',
                            columnLines: false,
                            deferRowRender: false,
                            forceFit: true,
                            store: 'lyjurlStore',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    id: 'urlnumber',
                                    width: 30,
                                    dataIndex: 'number',
                                    text: '编号',
                                    format: '0'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'webname',
                                    text: '网址名称'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 232,
                                    dataIndex: 'url',
                                    text: 'URL'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'searchField',
                                            fieldLabel: ''
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var mystore=Ext.StoreMgr.get('lyjurlStore'); //获得store对象
                                                //在load事件中添加参数
                                                mystore.load(
                                                {params:{
                                                    start:"0",
                                                    limit:"10",
                                                    searchField:Ext.getCmp('searchField').getValue()

                                                } 
                                            }
                                            );
                                            //Ext.Msg.alert('',Ext.getCmp('searchField_crawlurl').getValue());
                                            },
                                            text: '查找'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {
                                                var win=new Ext.Window({
                                                    height: 170,
                                                    width: 400,
                                                    id:'crawlurlWindow',
                                                    layout: {
                                                        type: 'absolute'
                                                    },
                                                    title: '添加',
                                                    modal:'true',
                                                    items: [
                                                    {
                                                        xtype: 'form',
                                                        height: 220,
                                                        jsonSubmit: true,
                                                        id:'crawlurl_add_Form',
                                                        layout: {
                                                            type: 'absolute'
                                                        },
                                                        bodyPadding: 10,
                                                        url: 'add_crawlurl',
                                                        title: '',
                                                        items: [
                                                        {
                                                            xtype: 'label',
                                                            x: 37,
                                                            y: 20,
                                                            text: '网站名称：'
                                                        },
                                                        {
                                                            xtype: 'label',
                                                            x: 40,
                                                            y: 55,
                                                            text: '网站URL：'
                                                        },

                                                        {
                                                            xtype: 'textfield',
                                                            id:'webName',
                                                            name:'webname',
                                                            x: 115,
                                                            y: 20,
                                                            width: 250,
                                                            fieldLabel: ''
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            id:'url',
                                                            name:'url',
                                                            x: 115,
                                                            y: 55,
                                                            width: 250,
                                                            fieldLabel: ''
                                                        },

                                                        {
                                                            xtype: 'button',
                                                            x: 115,
                                                            y: 100,
                                                            width: 50,
                                                            text: '确定',
                                                            handler:function()
                                                            {

                                                                var myform=Ext.getCmp('crawlurl_add_Form').getForm();    
                                                                if (myform.isValid()) { // make sure the form contains valid data before submitting
                                                                    myform.submit({
                                                                        success: function(form, action) {
                                                                            Ext.Msg.alert('提示', action.result.msg);

                                                                            var mystore=Ext.StoreMgr.get('lyjurlStore'); //获得store对象
                                                                            //在load事件中添加参数
                                                                            mystore.load(
                                                                            {params:{
                                                                                start:"0",
                                                                                limit:"10",
                                                                                searchField:Ext.getCmp('searchField').getValue()
                                                                            }} );
                                                                            win.close();
                                                                        },
                                                                        failure: function(form, action) {
                                                                            Ext.Msg.alert('提示', '保存失败！');
                                                                            win.close();
                                                                        }
                                                                    });
                                                                } else { 
                                                                    Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                                                                }


                                                                return;

                                                            }
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            handler: function(button, event) {
                                                                win.close();
                                                            },
                                                            x: 230,
                                                            y: 100,
                                                            width: 50,
                                                            text: '取消'
                                                        }
                                                        ]
                                                    }
                                                    ]
                                                });



                                                win.show();
                                            },
                                            text: '添加'
                                        },
                                        {
                                            xtype: 'button',
                                            handler: function(button, event) {

                                                var grid=this.up('grid');
                                                var record =grid.getSelectionModel().getSelection();

                                                if(record.length===0){
                                                    Ext.Msg.alert('提示','请先选择您要操作的行！');    
                                                    return;
                                                }
                                                else
                                                {
                                                    var ids='';
                                                    for(var i=0;i<record.length;i++)
                                                    {
                                                        ids+=record[i].get("number");
                                                        if(i<record.length-1)ids=ids+",";
                                                    }

                                                    Ext.Ajax.request({
                                                        waitMsg:'正在发送，请等待...',
                                                        url:'del_crawlurl',
                                                        params:{ids:ids},                          
                                                        success:function(response){
                                                            Ext.Msg.alert('success','删除成功！');                
                                                            var mystore=Ext.StoreMgr.get('lyjurlStore'); //获得store对象
                                                            //在load事件中添加参数
                                                            mystore.load(
                                                            {params:{
                                                                start:"0",
                                                                limit:"10",
                                                                searchField:Ext.getCmp('searchField').getValue()
                                                            }} );
                                                        },
                                                        failure:function(){
                                                            Ext.Msg.alert('failed','删除失败！');

                                                        }
                                                    });
                                                }

                                            },
                                            text: '删除'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    height: 30,
                                    width: 360,
                                    displayInfo: true,
                                    displayMsg: '显示{0} - {1} 条，共计{2}条',
                                    emptyMsg: '没有数据',
                                    store: 'lyjurlStore'
                                }
                            ],
                            listeners: {
                                cellclick: {
                                    fn: me.onGridpanelCellClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'south',
                    height: 130,
                    layout: {
                        align: 'middle',
                        pack: 'center',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    title: '设置信息采集周期',
                    items: [
                        {
                            xtype: 'container',
                            width: 712,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 287,
                                    fieldLabel: '现有信息采集周期'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: 5,
                                    width: 287,
                                    fieldLabel: '修改后信息采集周期',
                                    labelWidth: 115
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margins: '5',
                            width: 723,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'run_button',
                                    margin: 5,
                                    width: 75,
                                    text: '保存',
                                    listeners: {
                                        click: {
                                            fn: me.onRun_buttonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex===undefined || cellIndex<2) return;

        var win=new Ext.Window({
            height: 200,
            width: 400,
            id: 'lyjCrawlurlWindow_update',
            layout: {
                type: 'absolute'
            },
            title: '编辑',
            modal: true,
            items: [
            {
                xtype: 'form',
                id:'crawlurl_update_Form',
                height: 220,
                layout: {
                    type: 'absolute'
                },
                bodyPadding: 10,
                jsonSubmit: true,
                url: 'update_crawlurl',
                title: '',
                items: [
                {
                    xtype: 'label',
                    x: 37,
                    y: 20,
                    text: '网站名称：'
                },
                {
                    xtype: 'label',
                    x: 40,
                    y: 50,
                    text: '网站URL：'
                },
                {
                    xtype: 'textfield',
                    id:'webName_edit',
                    x: 115,
                    y: 20,
                    width: 250,
                    fieldLabel: '',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    id:'webURL_edit',
                    x: 115,
                    y: 50,
                    width: 250,
                    fieldLabel: '',
                    allowBlank: false
                },
                {
                    xtype: 'button',
                    x: 115,
                    y: 90,
                    width: 50,
                    text: '确定',
                    handler:function(){                     
                        var myform=Ext.getCmp('crawlurl_update_Form').getForm();    
                        if (myform.isValid()) { // make sure the form contains valid data before submitting
                            myform.submit({
                                success: function(form, action) {
                                    //Ext.Msg.alert('提示', action.result.msg);

                                    var mystore=Ext.StoreMgr.get('lyjurlStore'); //获得store对象
                                    //在load事件中添加参数
                                    mystore.load(
                                    {params:{
                                        start:"0",
                                        limit:"10",
                                        searchField:Ext.getCmp('searchField').getValue()

                                    }} );
                                    win.close();
                                },
                                failure: function(form, action) {
                                    //Ext.Msg.alert('提示', action.result.msg);
                                    win.close();
                                }
                            });
                        } else { 
                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                        }


                        return;

                    }
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        win.close();
                    },
                    x: 230,
                    y: 90,
                    width: 50,
                    text: '取消'
                }
                ]
            }
            ]
        });
        Ext.getCmp('webName_edit').setValue(record.data.webname);
        Ext.getCmp('webURL_edit').setValue(record.data.url);

        win.show();
    },

    onRun_buttonClick: function(button, e, eOpts) {
        Ext.Msg.alert('提示','要开始运行爬虫程序！');   
        Ext.Ajax.request({
            waitMsg:'正在启动，请等待...',
            url:'start_heritrix',

            success:function(response){
                Ext.Msg.alert('success','启动成功！');                

            },
            failure:function(){
                Ext.Msg.alert('failed','启动失败！');

            }
        });
    }

});