/*
 * File: app/view/Crawl2.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Crawl2', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.Crawl2',

    height: 440,
    html: '<iframe src=\'http://localhost:8090/main.jsp\' width=\'100%\' height=\'100%\'/>',
    width: 757,
    autoScroll: true,
    layout: {
        type: 'border'
    },
    title: '检索网站设置',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});