/*
 * File: app/view/gx.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.gx', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.gx',

    height: 687,
    id: 'gx',
    width: 849,
    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    title: '指标登记审核',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 20,
                    y: 30,
                    height: 210,
                    width: 780,
                    title: '待审核指标',
                    titleAlign: 'center',
                    store: 'z_zbdjsh',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 80,
                            dataIndex: 'ticketid',
                            text: '指标编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 81,
                            dataIndex: 'loginname',
                            text: '申请人'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'typelx',
                            text: '权属单位'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 82,
                            dataIndex: 'applydate',
                            text: '申请日期'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'area',
                            text: '规模'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'address',
                            text: '位置'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 78,
                            dataIndex: 'yyt',
                            text: '原土地用途'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 72,
                            dataIndex: 'checkstate',
                            text: '审核状态'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<input type='button' value='审核'>"
                            },
                            width: 72,
                            dataIndex: 'checkstate',
                            text: '操作'
                        }
                    ],
                    viewConfig: {
                        listeners: {
                            celldblclick: {
                                fn: me.onViewCellDblClick,
                                scope: me
                            }
                        }
                    },
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'z_zbdjsh'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    x: 20,
                    y: 260,
                    height: 300,
                    id: 'zbdjxx',
                    width: 380,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '指标登记信息',
                    jsonSubmit: true,
                    url: '',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 30,
                            width: 140,
                            fieldLabel: '指标编号',
                            labelWidth: 60,
                            name: 'ticketid'
                        },
                        {
                            xtype: 'textfield',
                            x: 190,
                            y: 130,
                            width: 170,
                            fieldLabel: '位置',
                            labelWidth: 60,
                            name: 'address'
                        },
                        {
                            xtype: 'textfield',
                            x: 190,
                            y: 80,
                            width: 170,
                            fieldLabel: '性质',
                            labelWidth: 60,
                            name: 'typelx'
                        },
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 80,
                            width: 140,
                            fieldLabel: '复垦编号',
                            labelWidth: 60,
                            name: 'fkid'
                        },
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 130,
                            width: 140,
                            fieldLabel: '规模',
                            labelWidth: 60,
                            name: 'area'
                        },
                        {
                            xtype: 'textfield',
                            x: 190,
                            y: 30,
                            width: 170,
                            fieldLabel: '权属单位',
                            labelWidth: 60,
                            name: 'company'
                        },
                        {
                            xtype: 'button',
                            x: 150,
                            y: 230,
                            width: 70,
                            text: '通过'
                        },
                        {
                            xtype: 'label',
                            x: 40,
                            y: 190,
                            html: '<a href=\'display/sfzm.jsp\' target=blank>身份证件</a>',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 160,
                            y: 190,
                            html: '<a href=\'display/qszm.jsp\' target=blank>权属证明</a>',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            x: 270,
                            y: 190,
                            html: '<a href=\'display/zbpz.jsp\' target=blank>指标凭证</a>',
                            text: ''
                        }
                    ]
                },
                {
                    xtype: 'form',
                    x: 420,
                    y: 260,
                    height: 300,
                    id: 'dkfkxx',
                    width: 380,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '地块复垦信息',
                    jsonSubmit: true,
                    url: 'dkfkxx',
                    items: [
                        {
                            xtype: 'displayfield',
                            x: 20,
                            y: 20,
                            width: 140,
                            fieldLabel: '项目编号',
                            labelWidth: 60,
                            name: 'applyId'
                        },
                        {
                            xtype: 'displayfield',
                            x: 20,
                            y: 90,
                            width: 140,
                            fieldLabel: '验收状态',
                            labelWidth: 60,
                            name: 'auditOpinion'
                        },
                        {
                            xtype: 'displayfield',
                            x: 190,
                            y: 90,
                            width: 160,
                            fieldLabel: '验收时间',
                            labelWidth: 60,
                            name: 'auditDate'
                        },
                        {
                            xtype: 'displayfield',
                            x: 190,
                            y: 20,
                            width: 160,
                            fieldLabel: '项目名称',
                            labelWidth: 60,
                            name: 'projectname'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onViewCellDblClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        var form1=Ext.getCmp('zbdjxx');
        var form2=Ext.getCmp('dkfkxx');
        form1.load(
        {
            url:'getzbdjxx' ,
            params:
            {
                ticketid:record.get('ticketid')
            }
        }
        );
        form2.load(
        {
            url:'getdkfkxx' ,
            params:
            {
                ticketid:record.get('ticketid')
            }
        }
        );


    }

});