/*
 * File: app/view/ht_bzjgl_lsjl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_bzjgl_lsjl', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ht_bzjgl_lsjl1',

    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    title: '历史记录',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    x: 40,
                    y: 60,
                    height: 320,
                    width: 730,
                    layout: {
                        type: 'fit'
                    },
                    title: '保证金记录',
                    titleAlign: 'center',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: 150,
                            title: '',
                            store: 'deposithistory',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'id',
                                    text: '编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'ticketid',
                                    text: '地票编号'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'operatedate',
                                    text: '日期',
                                    format: 'Y-m-d'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'comein',
                                    text: '转入'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'getout',
                                    text: '转出'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'yue',
                                    text: '余额'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'operator',
                                    text: '操作员'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 150,
                                    fieldLabel: '用户名称',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, event) {
                                        var s=Ext.StoreMgr.get('deposithistory');
                                        s.load();
                                    },
                                    width: 60,
                                    text: '查询'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'deposithistory'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});