/*
 * File: app/view/ht_bzjgl_cz.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_bzjgl_cz', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ht_bzjgl_cz1',

    id: 'czgl',
    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    title: '保证金交纳管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 20,
                    y: 40,
                    height: 340,
                    icon: 'imiages/deposit',
                    title: '保证金交纳管理',
                    titleAlign: 'center',
                    store: 'depositmanage',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 84,
                            dataIndex: 'loginName',
                            text: '用户名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 82,
                            dataIndex: 'ticketId',
                            text: '地票编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 82,
                            dataIndex: 'area',
                            text: '额度'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 72,
                            dataIndex: 'deposit',
                            text: '保证金'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'bidResult',
                            text: '竞标结果'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 76,
                            dataIndex: 'contract',
                            text: '合同状态'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return '等待确认';
                            },
                            width: 88,
                            dataIndex: 'returnstatus',
                            text: '保证金状态'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 88,
                            dataIndex: 'diedline',
                            text: '截止日期',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'actioncolumn',
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var name=record.get('loginName');
                                var ticketid=record.get('ticketId');
                                var filename=name+ticketid;
                                var pz=Ext.widget('bzjpz');
                                var i=Ext.getCmp('zfpz');
                                i.src='images/deposit.jpg';
                                pz.show();
                            },
                            width: 63,
                            align: 'center',
                            dataIndex: 'string',
                            icon: 'images/deposit.jpg'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<input type='button' value='已收到'>";

                            },
                            width: 88,
                            dataIndex: 'string',
                            text: '操作'
                        }
                    ],
                    viewConfig: {
                        listeners: {
                            cellclick: {
                                fn: me.onViewCellClick,
                                scope: me
                            }
                        }
                    },
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'depositmanage'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onViewCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {

        if(cellIndex=='10')
        {


            Ext.MessageBox.confirm('提醒','您确定要执行该操作码？',function(btn){
                if(btn=='yes')
                {
                    var d=Ext.StoreMgr.get('depositmanage');
                    d.load(
                    {
                        // url:'addticket',
                        url:'updatedepositreceived',
                        method:'post', 
                        contentType:'application/json',
                        //  dataType:'json',
                        // jsonSubmit:true,
                        headers:{
                            'Accept':'application/json',

                            'Content-Type':'application/json'
                        },

                        params:
                        {
                            //loginName:record.get('loginName'),
                            // ticketId:record.get('ticketId')
                            record:Ext.encode(record.getData())
                        }
                    }
                    );
                }





            });

        }
    }

});