/*
 * File: app/view/ht_jjjy_zgsh.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_jjjy_zgsh', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ht_jjjy_zgsh',

    height: 584,
    width: 806,
    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    title: '资格审核',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 20,
                    y: 40,
                    height: 310,
                    title: '资格审核',
                    titleAlign: 'center',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: '申请单位'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: '申请指标编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: '指标额度'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: '审核状态'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: '不良记录'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'bool',
                            text: '保证金'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '地票批次',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'button',
                                    width: 73,
                                    text: '通过'
                                },
                                {
                                    xtype: 'button',
                                    width: 73,
                                    text: '不通过'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 155,
                                    fieldLabel: '不良记录',
                                    labelWidth: 60
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});