/*
 * File: app/view/ht_jjjy_jygl1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_jjjy_jygl1', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.ht_jjjy_jygl1',

    height: 539,
    width: 795,
    title: '竞价交易管理<<交易管理',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '竞价交易管理>>挂牌管理',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 10,
                            width: 210,
                            fieldLabel: '本批次编号',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 280,
                            y: 10,
                            width: 200,
                            fieldLabel: '发布额度',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 40,
                            width: 200,
                            fieldLabel: '发布时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 280,
                            y: 40,
                            width: 190,
                            fieldLabel: '发布人',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 510,
                            y: 50,
                            width: 190,
                            fieldLabel: '开拍时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 530,
                            y: 10,
                            width: 170,
                            fieldLabel: '出让数量',
                            labelWidth: 60
                        },
                        {
                            xtype: 'gridpanel',
                            x: 10,
                            y: 110,
                            height: 270,
                            width: 700,
                            title: '交易管理',
                            titleAlign: 'center',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '地票编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '状态'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '地票额滴'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '当前最高价格'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '时间i信息'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '出价人次'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 62,
                                            text: '开拍'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 62,
                                            text: '结束'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 62,
                                            text: '撤销'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '竞价交易管理>>拍卖管理',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 10,
                            width: 150,
                            fieldLabel: '本批次编号',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 180,
                            y: 10,
                            width: 130,
                            fieldLabel: '发布额度',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 40,
                            width: 140,
                            fieldLabel: '发布时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 190,
                            y: 40,
                            width: 140,
                            fieldLabel: '发布人',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 350,
                            y: 40,
                            width: 130,
                            fieldLabel: '开拍时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 350,
                            y: 10,
                            width: 130,
                            fieldLabel: '分组数量',
                            labelWidth: 60
                        },
                        {
                            xtype: 'gridpanel',
                            x: 30,
                            y: 90,
                            height: 160,
                            title: '',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '地票编号'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '状态'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '数量信息'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '实时价格'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '时间信息'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '竞拍信息'
                                }
                            ],
                            selModel: Ext.create('Ext.selection.CheckboxModel', {

                            }),
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 50,
                                            text: '开拍'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 54,
                                            text: '下一轮'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 53,
                                            text: '结束'
                                        },
                                        {
                                            xtype: 'button',
                                            width: 54,
                                            text: '撤销'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            x: 500,
                            y: 10,
                            width: 60,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            emptyText: '全部'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            x: 150,
                            y: 291,
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});