/*
 * File: app/view/ht_jjjygl_fb.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_jjjygl_fb', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ht_jjjygl_fb',

    height: 805,
    id: 'articlepb',
    width: 1000,
    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    title: '指标出让公告发布',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 30,
                    y: 20,
                    width: 670,
                    fieldLabel: '信息名称',
                    name: 'articleName'
                },
                {
                    xtype: 'textfield',
                    x: 30,
                    y: 70,
                    width: 280,
                    fieldLabel: '信息作者',
                    name: 'articleAuthor'
                },
                {
                    xtype: 'textfield',
                    x: 460,
                    y: 70,
                    width: 200,
                    fieldLabel: '频道栏目',
                    name: 'channelId',
                    value: '指标发布',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 30,
                    y: 120,
                    width: 280,
                    fieldLabel: '信息来源',
                    name: 'articleSource'
                },
                {
                    xtype: 'htmleditor',
                    x: 30,
                    y: 180,
                    height: 400,
                    width: 750,
                    fieldLabel: '信息内容',
                    name: 'articleContent'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var myform = Ext.getCmp('articlepb').getForm();

                        if (myform.isValid()) { // make sure the form contains valid data before submitting
                            myform.submit({
                                url:'add_draftArticle',
                                success: function(form, action) {
                                    Ext.Msg.alert('success', '修改内容成功');


                                    var mystore = Ext.StoreMgr.get('ArticleDraftCJWTStore'); //获得store对象                                                   
                                    mystore.load();
                                    //win.close();

                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('failure', '修改内容失败');                           
                                    // win.close();
                                }
                            });
                        } else {
                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                        }


                    },
                    x: 180,
                    y: 620,
                    text: '信息发布'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var myform = Ext.getCmp('articlepb').getForm();

                        // Ext.getCmp('').setValues('');
                        if (myform.isValid()) { // make sure the form contains valid data before submitting
                            myform.submit({
                                url:'add_pubArticle',

                                success: function(form, action) {
                                    Ext.Msg.alert('success', '修改内容成功');

                                    var mystore = Ext.StoreMgr.get('ArticlePubZXDTStore'); //获得store对象                                                   
                                    mystore.load();

                                    // win.close();

                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('failure', '修改内容失败');                           
                                    //win.close();
                                }
                            });
                        } else {
                            Ext.Msg.alert('注意', '填写信息不能为空，请检查！');
                        }


                    },
                    x: 370,
                    y: 620,
                    text: '保存为草稿'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var myform=Ext.getCmp('articlepb');
                        myform.reSet();
                    },
                    x: 560,
                    y: 620,
                    text: '再写一篇'
                }
            ]
        });

        me.callParent(arguments);
    }

});