/*
 * File: app/view/ht_jjjy_fb.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_jjjy_fb', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.ht_jjjy_fb1',

    requires: [
        'MyApp.view.pmzbfb',
        'MyApp.view.jjjygl_gp'
    ],

    height: 462,
    width: 704,
    title: '竞价交易<<地票发布',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'pmzbfb'
                },
                {
                    xtype: 'myform1'
                }
            ]
        });

        me.callParent(arguments);
    }

});