/*
 * File: app/view/ht_jjjy_zbsh.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_jjjy_zbsh', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ht_jjjy_zbsh',

    height: 537,
    width: 802,
    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    title: '竞价交易管理>>中标审核',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 30,
                    y: 190,
                    height: 250,
                    width: 700,
                    title: '中标审核',
                    titleAlign: 'center',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: '地票组编号'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: '开拍日期'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: '结束日期'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'bool',
                            text: '中标单位'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'bool',
                            text: '管理员'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'bool',
                            text: '竞拍日志'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    }),
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    width: 79,
                                    text: '通过'
                                },
                                {
                                    xtype: 'button',
                                    width: 79,
                                    text: '不通过'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    x: 50,
                    y: 20,
                    height: 120,
                    layout: {
                        type: 'absolute'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'button',
                            x: 570,
                            y: 90,
                            width: 90,
                            text: '查    询'
                        },
                        {
                            xtype: 'datefield',
                            x: 500,
                            y: 10,
                            width: 160,
                            fieldLabel: '结束日期',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 260,
                            y: 10,
                            width: 160,
                            fieldLabel: '起始日期',
                            labelWidth: 60
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 10,
                            width: 190,
                            fieldLabel: '查询日期类型',
                            labelWidth: 80
                        },
                        {
                            xtype: 'textfield',
                            x: 10,
                            y: 60,
                            width: 180,
                            fieldLabel: '地票组编号',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            x: 260,
                            y: 60,
                            width: 160,
                            fieldLabel: '中标单位',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 490,
                            y: 60,
                            width: 170,
                            fieldLabel: '竞价管理员',
                            labelWidth: 70
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});