/*
 * File: app/view/ht_wqwb_wsqy.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_wqwb_wsqy', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.qt_dzjy_wsqy',

    height: 655,
    id: 'qt_dzjy_wsqy',
    width: 886,
    layout: {
        type: 'absolute'
    },
    title: '网上签约',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 10,
                    y: 50,
                    height: 380,
                    style: {
                        lineheight: '200'
                    },
                    width: 870,
                    bodyStyle: {
                        lineHeight: '200'
                    },
                    title: '待签约地票',
                    titleAlign: 'center',
                    titleCollapse: false,
                    columnLines: false,
                    store: 'sign',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 45,
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 92,
                            dataIndex: 'ticketid',
                            text: '地票编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'amount',
                            text: '额度'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'price',
                            text: '中标价格'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'totalprice',
                            text: '总价'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 96,
                            dataIndex: 'winner',
                            text: '中标单位'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'windate',
                            text: '中标日期'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'contractid',
                            text: '合同编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 71,
                            dataIndex: 'contractstatus',
                            text: '客户确认'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<button><label>邀请签约</label></button>";
                            },
                            height: 0,
                            text: '操作'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<button href="+value+"><label>查看合同</label></button>";
                            },
                            height: 0,
                            dataIndex: 'contractcontent',
                            text: '操作'
                        }
                    ],
                    viewConfig: {
                        style: {
                            lineHeight: '200'
                        }
                    },
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'sign'
                        }
                    ],
                    listeners: {
                        cellclick: {
                            fn: me.onGridpanelCellClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'label',
                    x: 10,
                    y: 520,
                    text: '温馨提示：'
                },
                {
                    xtype: 'label',
                    x: 80,
                    y: 520,
                    height: 20,
                    text: '1）如果生成网签号则说明合同签订成功'
                },
                {
                    xtype: 'label',
                    x: 80,
                    y: 550,
                    height: 20,
                    text: '2）在截止日期前不能签订合同则视为放弃'
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex=='9')
        {

            var sign=Ext.StoreMgr.get('sign');

            Ext.Ajax.request(
            {
                url:'updatesign',
                method:'post', 
                headers:{


                    'Content-Type':'application/json'
                },


                success:function(response){
                    var result=Ext.decode(response.responseText);
                    Ext.MessageBox.alert('信息',result.msg,function(btn){
                        sign.load();
                    });
                },
                failure:function(){
                    Ext.MessageBox.alert('错误','操作失败！');
                },
                params: Ext.encode(record.getData())
                // record:record.getData()


            }

            );

        }
        if(cellIndex=='10')
        {
            //alert(record.get('contractcontent'));
            //window.open(record.get('contractcontent'));   
            window.open(decodeURI(record.get('contractcontent'),'gbk'));
        }
    }

});