/*
 * File: app/view/ht_wqwb_dagl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_wqwb_dagl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ht_wqwb_dagl',

    height: 629,
    id: 'ht_wqwb_dagl',
    width: 925,
    autoScroll: true,
    layout: {
        type: 'fit'
    },
    title: '备案记录',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 310,
                    width: 700,
                    title: '',
                    titleAlign: 'center',
                    store: 'record',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 129,
                            dataIndex: 'ticketid',
                            text: '地票编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'winner',
                            text: '中标单位'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 112,
                            dataIndex: 'amount',
                            text: '额度'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 112,
                            dataIndex: 'price',
                            text: '单价'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 75,
                            dataIndex: 'totalprice',
                            text: '总价'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 126,
                            dataIndex: 'windate',
                            text: '中标日期'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<button><label>查看合同</label></button>";
                            },
                            width: 72,
                            dataIndex: 'contractcontent',
                            text: '合同'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<button><label>查看凭证</label></button>";
                            },
                            width: 75,
                            dataIndex: 'certification',
                            text: '证书'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'record'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});