/*
 * File: app/view/ht_wqwb_jysh.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_wqwb_jysh', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ht_wqwb_jysh1',

    height: 724,
    width: 1056,
    autoScroll: true,
    layout: {
        type: 'fit'
    },
    title: '交易审核',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 340,
                    width: 700,
                    title: '',
                    titleAlign: 'center',
                    store: 'jycheck',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 152,
                            dataIndex: 'ticketid',
                            text: '地票编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 145,
                            dataIndex: 'winner',
                            text: '中标单位'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 128,
                            dataIndex: 'amount',
                            text: '额度'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 119,
                            dataIndex: 'price',
                            text: '中标价格'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 115,
                            dataIndex: 'netsignid',
                            text: '网签号'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var display='';
                                var result=value.split(",");
                                for(var i=0;i<result.length;i++){
                                    display=display+"<label>"+result[i]+"</label><br>";

                                }
                                //alert(display);
                                return display;
                            },
                            width: 126,
                            dataIndex: 'material',
                            text: '上交材料'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 133,
                            dataIndex: 'jycheck',
                            text: '审核状态'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return "<button><label>通过</label></button>";
                            },
                            width: 133,
                            dataIndex: 'string',
                            text: '审核操作'
                        }
                    ],
                    listeners: {
                        cellclick: {
                            fn: me.onGridpanelCellClick,
                            scope: me
                        }
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'jycheck'
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelCellClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(cellIndex=='7')
        {

            Ext.MessageBox.confirm('信息','您确定要执行通过操作吗？',function(btn){
                //alert(btn);
                if(btn=='yes')
                {
                    //alert('shenhe');
                    var check=Ext.StoreMgr.get('jycheck');

                    Ext.Ajax.request(
                    {

                        url:'updatecheck',
                        method:'post', 
                        headers:{


                            'Content-Type':'application/json'
                        },


                        success:function(response){                    
                            check.load();
                        },

                        failure:function(){
                            Ext.MessageBox.alert('错误','操作失败！');
                        },
                        params: Ext.encode(record.getData())
                        // record:record.getData()

                    }
                    ); 
                }

            });


        }
    }

});