/*
 * File: app/view/ht_wqwb_htmb.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ht_wqwb_htmb', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ht_wqwb_htmb1',

    height: 606,
    width: 776,
    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    title: '合同模板',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textareafield',
                    x: 10,
                    y: 80,
                    height: 432,
                    width: 720,
                    fieldLabel: '内容',
                    labelWidth: 40
                },
                {
                    xtype: 'button',
                    x: 250,
                    y: 540,
                    width: 70,
                    text: '确定'
                },
                {
                    xtype: 'button',
                    x: 400,
                    y: 540,
                    width: 70,
                    text: '修改'
                },
                {
                    xtype: 'textfield',
                    x: 50,
                    y: 40,
                    width: 170,
                    fieldLabel: '合同编号',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    x: 250,
                    y: 40,
                    width: 160,
                    fieldLabel: '甲方',
                    labelWidth: 60
                },
                {
                    xtype: 'textfield',
                    x: 460,
                    y: 40,
                    fieldLabel: '乙方',
                    labelWidth: 60
                }
            ]
        });

        me.callParent(arguments);
    }

});