/*
 * File: app/view/jjjygl_gp.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.jjjygl_gp', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform1',

    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    title: '竞价交易管理>>挂牌地票发布',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    x: 20,
                    y: 0,
                    text: '当前信息库地票总额:'
                },
                {
                    xtype: 'label',
                    x: 140,
                    y: 0,
                    text: '5000亩'
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: -3,
                    width: 160,
                    fieldLabel: '本批次发布额度'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 20,
                    width: 160,
                    fieldLabel: '设置本批次组数'
                },
                {
                    xtype: 'button',
                    x: 220,
                    y: 20,
                    width: 60,
                    text: '确    定'
                },
                {
                    xtype: 'label',
                    x: 310,
                    y: 20,
                    height: 20,
                    text: '本批次编号为：'
                },
                {
                    xtype: 'label',
                    x: 450,
                    y: 20,
                    height: 20,
                    text: '请详细设置每组属性'
                },
                {
                    xtype: 'label',
                    x: 390,
                    y: 20,
                    text: '2012-gP-1'
                },
                {
                    xtype: 'panel',
                    x: 10,
                    y: 50,
                    height: 250,
                    width: 250,
                    layout: {
                        type: 'absolute'
                    },
                    title: '编号',
                    titleAlign: 'center',
                    items: [
                        {
                            xtype: 'button',
                            x: 100,
                            y: 190,
                            text: '挂牌发布'
                        },
                        {
                            xtype: 'combobox',
                            x: 90,
                            y: 20,
                            width: 150,
                            fieldLabel: '地票额度',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 90,
                            y: 80,
                            width: 150,
                            fieldLabel: '截止日期',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 90,
                            y: 140,
                            width: 150,
                            fieldLabel: '设置低价',
                            labelWidth: 60
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    x: 290,
                    y: 50,
                    height: 250,
                    width: 250,
                    layout: {
                        type: 'absolute'
                    },
                    title: '编号',
                    titleAlign: 'center',
                    items: [
                        {
                            xtype: 'button',
                            x: 100,
                            y: 190,
                            text: '挂牌发布'
                        },
                        {
                            xtype: 'combobox',
                            x: 90,
                            y: 20,
                            width: 150,
                            fieldLabel: '地票额度',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 90,
                            y: 80,
                            width: 150,
                            fieldLabel: '截止日期',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 90,
                            y: 140,
                            width: 150,
                            fieldLabel: '设置低价',
                            labelWidth: 60
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    x: 95,
                    y: 298,
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                }
            ]
        });

        me.callParent(arguments);
    }

});