/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.infoArticleZXDTTab'
    ],

    id: 'myViewPort',
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    autoRender: false,
                    id: 'htglTabPanelMain',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'infoArticleZXDTTab'
                        }
                    ],
                    listeners: {
                        show: {
                            fn: me.onHtglTabPanelMainShow,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 150,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'label',
                            html: '<a href="j_spring_security_logout">退出      </a>'
                        },
                        {
                            xtype: 'label',
                            html: '<a href="http://localhost:8080/tdlz_dzjy02/index.html" target="blank">          集体建设用地电子交易系统</a>',
                            text: ''
                        },
                        {
                            xtype: 'label',
                            html: '<a href="http://localhost:8080/tdlz_homeWebSite/" target="blank">       门户网站</a>',
                            text: ''
                        },
                        {
                            xtype: 'image',
                            height: 201,
                            width: 201,
                            src: 'images/title_htgl.png'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    width: 150,
                    layout: {
                        type: 'accordion'
                    },
                    collapsible: true,
                    title: '管理面板',
                    items: [
                        {
                            xtype: 'treepanel',
                            height: 102,
                            title: '信息发布推送',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'infoArticleZXDTTab',
                                        text: '最新动态',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleTZGGTab',
                                        text: '通知公告',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleNDZCTab',
                                        text: '供地信息',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleNDZRTab',
                                        text: '需求信息',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleZJJYTab',
                                        text: '最新交易',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleJYLCTab',
                                        text: '交易流程',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'infoArticleQRCodeTab',
                                        text: '二维码管理',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '地票审核入库',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'gx',
                                        text: '指标登记审核',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_shjd_dagl1',
                                        text: '档案管理',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange11,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '保证金管理',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'ht_bzjgl_cz1',
                                        text: '充值管理',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_bzjgl_tk1',
                                        text: '退款管理',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_bzjgl_lsjl1',
                                        text: '历史记录',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '竞价交易管理',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'ht_jjjygl_fb',
                                        text: '发布公告',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'pmzbfb',
                                        text: '指标发布',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_jjjy_zgsh',
                                        text: '资格审核',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_jjjy_jygl1',
                                        text: '交易管理',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_jjjy_zbsh',
                                        text: '中标审核',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '网签网备',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'qt_dzjy_wsqy',
                                        text: '网上签约',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_wqwb_jysh1',
                                        text: '交易审核',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_wqwb_fzba1',
                                        text: '发证备案',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ht_wqwb_dagl',
                                        text: '档案管理',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange11111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '交易态势分析',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'TaishiFind',
                                        text: '交易态势查询',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiPrice',
                                        text: '按交易价格分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiVolume',
                                        text: '按交易量分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiNumber',
                                        text: '按交易次数分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiArea',
                                        text: '按交易区域分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'TaishiAlarm',
                                        text: '交易态势异常分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange111111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '收益分配溯源',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: 'ShouyiFind_Hetong',
                                        text: '收益查询',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ShouyiRegister',
                                        text: '收益登记',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ShouyiStat_Nonghu',
                                        text: '统计分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    },
                                    {
                                        id: 'ShouyiAlarm',
                                        text: '异常分析',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange1111111,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: '信息检索与统计',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        id: '',
                                        text: '信息检索设置',
                                        icon: 'images/tubiao.png',
                                        children: [
                                            {
                                                id: 'Crawl',
                                                text: '检索网站设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'Extract',
                                                text: '字段存储设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            },
                                            {
                                                id: 'Keywords',
                                                text: '查询主题词设置',
                                                icon: 'images/tubiao.jpg',
                                                leaf: true
                                            }
                                        ]
                                    },
                                    {
                                        id: 'ccQueryStatisticsTab',
                                        text: '查询与统计',
                                        icon: 'images/tubiao.png',
                                        leaf: true
                                    }
                                ]
                            },
                            rootVisible: false,
                            viewConfig: {

                            },
                            listeners: {
                                selectionchange: {
                                    fn: me.onTreepanelSelectionChange2,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onHtglTabPanelMainShow: function(component, eOpts) {
        Ext.Ajax.request({
            url:'timer_creat_xml'

        });
    },

    onTreepanelSelectionChange1: function(model, selected, eOpts) {
        //var xtype = selected[0].get('id');   
        //Ext.MessageBox.alert('xtype',xtype);
        //var tabPanel=Ext.ComponentQuery.query('tabpanel')[0];
        //tabPanel.removeAll(true);
        //tabPanel.add(Ext.widget(xtype));
        // Ext.MessageBox.alert('info444',title);

        var xtype = selected[0].get('id');   
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);


        var xtypes=xtype.split(",");
        for(var i=0;i<xtypes.length;i++){
            myTabPanel.add(Ext.widget(xtypes[i]));
        }

        var mywin=Ext.create('Ext.window.Window',{
            title: '农地转入信息推送',
            minWidth: 700,
            minHeight: 380,
            layout: 'fit',
            items: [Ext.widget(xtypes[1])]
        });
        mywin.show();
    },

    onTreepanelSelectionChange11: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        //Ext.MessageBox.alert();
        myTabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange1111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');  
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));

    },

    onTreepanelSelectionChange11111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange111111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
    },

    onTreepanelSelectionChange1111111: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');   
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
        if(xtype=='ShouyiStat_Nonghu'){
            myTabPanel.add(Ext.widget('ShouyiStat_Jianshe')); 
        }
        if(xtype=='ShouyiFind_Hetong'){
            myTabPanel.add(Ext.widget('ShouyiFind_Zijin')); 
        }

    },

    onTreepanelSelectionChange2: function(model, selected, eOpts) {
        var xtype = selected[0].get('id');  
        //Ext.Msg.alert("",xtype);
        var myTabPanel = Ext.getCmp('htglTabPanelMain');
        //Ext.Msg.alert("",myTabPanel.id);
        myTabPanel.removeAll(true);
        myTabPanel.add(Ext.widget(xtype));
    }

});