/*
 * File: app/view/quotaKeywords.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.quotaKeywords', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.quotaKeywords',

    autoScroll: true,
    layout: {
        type: 'border'
    },
    title: '查询主题词设置>>建设指标',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'container',
                            height: 267,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    height: 226,
                                    title: '现有查询主题词',
                                    hideHeaders: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 336,
                                            dataIndex: 'string',
                                            text: 'String'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    width: 67,
                                    layout: {
                                        align: 'center',
                                        pack: 'center',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            cls: 'x-btn-text-icon',
                                            height: 30,
                                            width: 30,
                                            icon: 'images/1.jpg',
                                            iconAlign: 'bottom',
                                            scale: 'large',
                                            text: ''
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            height: 30,
                                            width: 30,
                                            icon: 'images/2.jpg',
                                            iconAlign: 'bottom',
                                            scale: 'large',
                                            text: ''
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    height: 226,
                                    width: 333,
                                    title: '添加查询主题词',
                                    hideHeaders: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 336,
                                            dataIndex: 'string',
                                            text: 'String'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 100,
                            layout: {
                                align: 'middle',
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    text: '保存设置'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});