/*
 * File: app/view/ShouyiAlarm_Canshu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ShouyiAlarm_Canshu', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ShouyiAlarm_Canshu',

    height: 500,
    width: 557,
    layout: {
        type: 'absolute'
    },
    title: '收益分配异常监测参数设置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 30,
                    width: 240,
                    fieldLabel: '交易结束后农户资金到账最长天数',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 90,
                    width: 240,
                    fieldLabel: '每亩建设成本最高价格',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 140,
                    width: 240,
                    fieldLabel: '建设单位最高收益比例',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 190,
                    width: 240,
                    fieldLabel: '政府最高收益比例',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 240,
                    width: 240,
                    fieldLabel: '农户最高收益比例',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 290,
                    width: 240,
                    fieldLabel: '资金流动手续可允许最大缺失项数',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 350,
                    width: 240,
                    fieldLabel: '举报次数',
                    labelWidth: 150
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var tabs = this.up('tabpanel');
                        tabs.removeAll(true);
                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                        var newtab = tabs.add(Ext.widget('ShouyiAlarm'));
                        Ext.MessageBox.confirm('参数保存框','参数保存成功！',function(btn){

                        });

                    },
                    x: 120,
                    y: 420,
                    width: 90,
                    text: '保存'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var tabs = this.up('tabpanel');
                        tabs.removeAll(true);
                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                        var newtab = tabs.add(Ext.widget('ShouyiAlarm'));


                    },
                    x: 270,
                    y: 420,
                    width: 90,
                    text: '取消'
                }
            ]
        });

        me.callParent(arguments);
    }

});