/*
 * File: app/view/ShouyiFind_Zijin.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ShouyiFind_Zijin', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ShouyiFind_Zijin',

    height: 497,
    id: 'ShouyiFind_Zijin',
    width: 691,
    layout: {
        type: 'border'
    },
    title: '资金流动信息查询',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 124,
                    layout: {
                        type: 'absolute'
                    },
                    title: '选择查询条件',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 460,
                            y: 20,
                            id: 'ShouyiFindZijinField',
                            width: 180,
                            fieldLabel: '关键词',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 20,
                            y: 20,
                            id: 'ShouyiFindZijinDateStart',
                            width: 180,
                            fieldLabel: '起始时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 240,
                            y: 20,
                            id: 'ShouyiFindZijinDateEnd',
                            width: 180,
                            fieldLabel: '结束时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var getDate1 = Ext.util.Format.date(Ext.getCmp('ShouyiFindZijinDateStart').getValue(),'Y-m-d');
                                var getDate2 = Ext.util.Format.date(Ext.getCmp('ShouyiFindZijinDateEnd').getValue(),'Y-m-d');
                                var getKeyword1 = Ext.getCmp('ShouyiFindZijinField').getValue();
                                var mystore=Ext.StoreMgr.get('ShouyiFind_Zijin'); //获得store对象
                                //在load事件中添加参数
                                mystore.load(
                                {params:{
                                    start:"0",
                                    limit:"25",
                                    searchDate1:getDate1,
                                    searchDate2:getDate2, 
                                    searchKeyword1:getKeyword1
                                } 
                            }
                            );
                            },
                            x: 90,
                            y: 60,
                            width: 60,
                            text: '查询'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var grid = Ext.getCmp('ShouyiZijinTable');
                                var record = grid.getSelectionModel().getSelection();
                                if(record.length === 0){
                                    Ext.Msg.alert('提示','请先选择您要操作的行！');    
                                    return;

                                }else{

                                    var  tablexh =new Array(record.length);
                                    for(var i = 0;i<record.length;i++){
                                        tablexh[i] = record[i].get("xh");

                                    }

                                    Ext.Ajax.request({
                                        url:'getBenefitList18',
                                        params:{tablexh:tablexh},

                                        success:function(response){
                                            Ext.Msg.alert('删除提示','该条信息已成功删除！');
                                            var mystore = Ext.StoreMgr.get('ShouyiFind_Zijin');
                                            mystore.load();
                                        }

                                    });

                                }
                            },
                            x: 310,
                            y: 60,
                            width: 60,
                            text: '删除'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var getDate1 = Ext.util.Format.date(Ext.getCmp('ShouyiFindZijinDateStart').getValue(),'Y-m-d');
                                var getDate2 = Ext.util.Format.date(Ext.getCmp('ShouyiFindZijinDateEnd').getValue(),'Y-m-d');
                                var getKeyword1 = Ext.getCmp('ShouyiFindZijinField').getValue();
                                var mystore=Ext.StoreMgr.get('ShouyiFind_Zijin'); //获得store对象
                                //在load事件中添加参数
                                mystore.load(
                                {params:{
                                    start:"0",
                                    limit:"25",
                                    searchDate1:getDate1,
                                    searchDate2:getDate2, 
                                    searchKeyword1:getKeyword1
                                } 
                            }
                            );
                            },
                            x: 530,
                            y: 60,
                            width: 60,
                            text: '修改'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    id: 'ShouyiZijinTable',
                    title: '资金流动列表',
                    store: 'ShouyiFind_Zijin',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 39,
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'htbh',
                            text: '合同编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'pjh',
                            text: '票据号'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'jysj',
                            text: '交易时间'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'zjlcf',
                            text: '资金流出方'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'zjlrf',
                            text: '资金流入方'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 61,
                            dataIndex: 'je',
                            text: '金额'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'yt',
                            text: '用途'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'jbr',
                            text: '经办人'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'scsmj',
                            text: '扫描件'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'dzqr',
                            text: '到账确认'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'ShouyiFind_Zijin'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    })
                }
            ]
        });

        me.callParent(arguments);
    }

});