/*
 * File: app/view/ShouyiRegister.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ShouyiRegister', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ShouyiRegister',

    autoRender: true,
    autoShow: true,
    height: 485,
    id: 'ShouyiRegister',
    width: 567,
    autoScroll: true,
    layout: {
        type: 'absolute'
    },
    title: '收益额度信息登记',
    jsonSubmit: true,
    url: 'getBenefitList12',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            jsonSubmit: true,
            url: 'getBenefitList12'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 140,
                    id: 'zjlcf',
                    fieldLabel: '资金流出方',
                    name: 'zjlcf'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 200,
                    id: 'yt',
                    fieldLabel: '用途',
                    name: 'yt'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 140,
                    id: 'zjlrf',
                    fieldLabel: '资金流入方',
                    name: 'zjlrf'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 200,
                    id: 'jbr',
                    fieldLabel: '经办人',
                    name: 'jbr'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 20,
                    id: 'pjh',
                    fieldLabel: '票据号',
                    name: 'pjh'
                },
                {
                    xtype: 'textfield',
                    x: 300,
                    y: 80,
                    id: 'je',
                    fieldLabel: '金额',
                    name: 'je'
                },
                {
                    xtype: 'datefield',
                    x: 20,
                    y: 80,
                    id: 'jysj',
                    fieldLabel: '交易时间',
                    name: 'jysj'
                },
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 260,
                    autoRender: false,
                    id: 'dzqr',
                    fieldLabel: '到账确认',
                    name: 'dzqr',
                    emptyText: '请选择',
                    displayField: 'name',
                    queryMode: 'local',
                    store: 'ShouyiCombox',
                    valueField: 'value'
                },
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 20,
                    autoRender: false,
                    id: 'htbh',
                    fieldLabel: '合同编号',
                    name: 'htbh',
                    emptyText: '请选择',
                    displayField: 'value',
                    queryMode: 'local',
                    store: 'ShouyiRegisterHtbh',
                    valueField: 'value'
                },
                {
                    xtype: 'filefield',
                    x: 300,
                    y: 260,
                    id: 'scsmj',
                    width: 240,
                    fieldLabel: '票据扫描件',
                    name: 'scsmj',
                    buttonText: '选择'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {

                        var form = Ext.getCmp('ShouyiRegister').getForm(); // get the basic form
                        if (form.isValid()) { // make sure the form contains valid data before submitting
                            form.submit({
                                url:'getBenefitList12',
                                success: function(form, action) {
                                    Ext.Msg.alert('保存成功', action.result.msg);
                                    var mystore = Ext.StoreMgr.get('ShouyiFind_Zijin'); //获得store对象                                                   
                                    mystore.load();
                                },
                                failure: function(form, action) {
                                    Ext.Msg.alert('保存失败', action.result.msg);
                                }
                            });
                        } else { // display error alert if the data is invalid
                            Ext.Msg.alert('Invalid Data', 'Please correct form errors.');
                        }

                    },
                    x: 230,
                    y: 330,
                    width: 90,
                    text: '保存'
                }
            ]
        });

        me.callParent(arguments);
    }

});