/*
 * File: app/view/ShouyiStat_Nonghu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ShouyiStat_Nonghu', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ShouyiStat_Nonghu',

    height: 485,
    width: 695,
    layout: {
        type: 'border'
    },
    title: '农户收益分析',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'north',
                    height: 124,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '选择查询条件',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 20,
                            y: 60,
                            id: 'ShouyiStatNonghuField',
                            width: 180,
                            fieldLabel: '关键词',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 20,
                            y: 20,
                            id: 'ShouyiStatNonghuDateStart',
                            width: 180,
                            fieldLabel: '起始时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 300,
                            y: 20,
                            id: 'ShouyiStatNonghuDateEnd',
                            width: 180,
                            fieldLabel: '结束时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var getDate1 = Ext.util.Format.date(Ext.getCmp('ShouyiStatNonghuDateStart').getValue(),'Y-m-d');
                                var getDate2 = Ext.util.Format.date(Ext.getCmp('ShouyiStatNonghuDateEnd').getValue(),'Y-m-d');
                                var getKeyword1 = Ext.getCmp('ShouyiStatNonghuField').getValue();
                                var mystore=Ext.StoreMgr.get('ShouyiStat_Nonghu'); //获得store对象
                                //在load事件中添加参数
                                mystore.load(
                                {params:{
                                    start:"0",
                                    limit:"25",
                                    searchDate1:getDate1,
                                    searchDate2:getDate2, 
                                    searchKeyword1:getKeyword1
                                } 
                            }
                            );
                            },
                            x: 370,
                            y: 60,
                            width: 60,
                            text: '查询'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    title: '农户收益分配统计表',
                    store: 'ShouyiStat_Nonghu',
                    columns: [
                        {
                            xtype: 'rownumberer',
                            width: 46,
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 67,
                            dataIndex: 'nhxm',
                            text: '农户姓名'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 91,
                            dataIndex: 'yydkbh',
                            text: '拥有地块编号'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'lzsj',
                            text: '流转时间'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 77,
                            dataIndex: 'lzl',
                            text: '流转量（亩）'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 144,
                            dataIndex: 'lzlbl',
                            text: '所占该地票的百分比（%）'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 63,
                            dataIndex: 'sy',
                            text: '收益（万）'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 160,
                            dataIndex: 'sybl',
                            text: '所占农户总收益的百分比（%）'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'ShouyiStat_Nonghu'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});