/*
 * File: app/view/TaishiArea.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TaishiArea', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.TaishiArea',

    height: 499,
    width: 692,
    layout: {
        type: 'border'
    },
    title: '按交易区域分析',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    title: '按交易区域分析图',
                    dockedItems: [
                        {
                            xtype: 'image',
                            dock: 'top',
                            height: 295,
                            width: 688,
                            src: 'area.jpg'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'north',
                    height: 150,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '查询条件',
                    items: [
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 20,
                            width: 180,
                            fieldLabel: '起始时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 210,
                            y: 20,
                            width: 180,
                            fieldLabel: '结束时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'button',
                            x: 490,
                            y: 70,
                            width: 60,
                            text: '查询'
                        },
                        {
                            xtype: 'combobox',
                            x: 420,
                            y: 20,
                            width: 180,
                            fieldLabel: '交易区域',
                            labelWidth: 60
                        },
                        {
                            xtype: 'radiogroup',
                            x: 10,
                            y: 70,
                            width: 380,
                            fieldLabel: '显示内容',
                            labelWidth: 60,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '交易量'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '交易次数'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '交易价格'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});