/*
 * File: app/view/TaishiNumber.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TaishiNumber', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.TaishiNumber',

    height: 499,
    width: 693,
    layout: {
        type: 'border'
    },
    title: '按交易次数分析',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'north',
                    height: 139,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '查询条件',
                    items: [
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 20,
                            id: 'TaishiNumberDateField1',
                            width: 180,
                            fieldLabel: '起始时间',
                            labelWidth: 60,
                            name: ''
                        },
                        {
                            xtype: 'datefield',
                            x: 270,
                            y: 20,
                            id: 'TaishiNumberDateField2',
                            width: 180,
                            fieldLabel: '结束时间',
                            labelWidth: 60,
                            name: ''
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 70,
                            id: 'TaishiNumberTextField',
                            width: 180,
                            fieldLabel: '交易区域',
                            labelWidth: 60,
                            name: 'TaishiNumberTextField',
                            emptyText: '请选择区域',
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'TaishiNumberCombox',
                            valueField: 'value'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var getDate1 = Ext.util.Format.date(Ext.getCmp('TaishiNumberDateField1').getValue(),'Y-m-d');
                                var getDate2 = Ext.util.Format.date(Ext.getCmp('TaishiNumberDateField2').getValue(),'Y-m-d');
                                var getKeyword = Ext.getCmp('TaishiNumberTextField').getRawValue();
                                var mystore=Ext.StoreMgr.get('TaishiNumber_Pie'); //获得store对象
                                //在load事件中添加参数
                                mystore.load(
                                {params:{
                                    searchDate1:getDate1,
                                    searchDate2:getDate2, 
                                    searchKeyword:getKeyword
                                } 
                            }
                            );
                            },
                            x: 340,
                            y: 70,
                            width: 60,
                            text: '查询'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: {
                        type: 'absolute'
                    },
                    title: '各方交易次数分析图',
                    items: [
                        {
                            xtype: 'chart',
                            x: 0,
                            y: 10,
                            autoRender: true,
                            height: 280,
                            width: 340,
                            animate: true,
                            insetPadding: 20,
                            store: 'TaishiNumber_Pie',
                            series: [
                                {
                                    type: 'pie',
                                    label: {
                                        field: 'taiarea',
                                        display: 'none',
                                        contrast: true,
                                        font: '12px Arial'
                                    },
                                    showInLegend: true,
                                    angleField: 'taicount'
                                }
                            ],
                            legend: {
                                position: 'right'
                            }
                        },
                        {
                            xtype: 'chart',
                            x: 340,
                            y: 10,
                            height: 280,
                            width: 351,
                            animate: true,
                            insetPadding: 20,
                            store: 'TaishiNumber_Pie',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'taiarea'
                                    ],
                                    position: 'left',
                                    title: '交易区域'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'taicount'
                                    ],
                                    majorTickSteps: 1,
                                    minorTickSteps: 1,
                                    position: 'bottom',
                                    title: '交易次数',
                                    decimals: 0
                                }
                            ],
                            series: [
                                {
                                    type: 'column',
                                    xField: 'taiarea',
                                    yField: 'taicount',
                                    type: 'bar'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});