/*
 * File: app/view/TaishiAlarm_Chart.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TaishiAlarm_Chart', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.TaishiAlarm_Chart',

    height: 500,
    width: 692,
    layout: {
        type: 'border'
    },
    title: '交易态势异常分析',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'datefield',
                            id: 'TaishiAlarmDateStart1',
                            width: 165,
                            fieldLabel: '起始时间',
                            labelWidth: 60,
                            enforceMaxLength: false,
                            useStrict: false
                        },
                        {
                            xtype: 'datefield',
                            id: 'TaishiAlarmDateEnd1',
                            width: 165,
                            fieldLabel: '结束时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'combobox',
                            id: 'TaishiAlarmTextField1',
                            width: 165,
                            fieldLabel: '交易区域',
                            labelWidth: 60,
                            name: 'TaishiAlarmTextField',
                            emptyText: '请选择区域',
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'TaishiAlarmCombox',
                            valueField: 'value'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var getDate1 = Ext.util.Format.date(Ext.getCmp('TaishiAlarmDateStart1').getValue(),'Y-m-d');
                                var getDate2 = Ext.util.Format.date(Ext.getCmp('TaishiAlarmDateEnd1').getValue(),'Y-m-d');
                                var getKeyword = Ext.getCmp('TaishiAlarmTextField1').getRawValue();
                                var mystore=Ext.StoreMgr.get('TaishiAlarm_Pie'); //获得store对象
                                //在load事件中添加参数
                                mystore.load(
                                {params:{
                                    searchDate1:getDate1,
                                    searchDate2:getDate2,
                                    searchKeyword:getKeyword
                                } 
                            }
                            );
                            },
                            width: 60,
                            text: '统计分析'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var tabs = this.up('tabpanel');
                                tabs.removeAll(true);
                                //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到交易态势异常分析的页面
                                var newtab = tabs.add(Ext.widget('TaishiAlarm'));
                            },
                            width: 60,
                            text: '返回'
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'chart',
                    region: 'west',
                    autoRender: true,
                    width: 338,
                    animate: true,
                    insetPadding: 20,
                    store: 'TaishiAlarm_Pie',
                    series: [
                        {
                            type: 'pie',
                            label: {
                                field: 'yctype',
                                display: 'none',
                                contrast: true,
                                font: '12px Arial'
                            },
                            showInLegend: true,
                            angleField: 'yccount'
                        }
                    ],
                    legend: {
                        position: 'right'
                    }
                },
                {
                    xtype: 'chart',
                    region: 'west',
                    width: 351,
                    animate: true,
                    insetPadding: 20,
                    store: 'TaishiAlarm_Pie',
                    axes: [
                        {
                            type: 'Category',
                            fields: [
                                'yctype'
                            ],
                            position: 'left',
                            title: '交易态势异常类型'
                        },
                        {
                            type: 'Numeric',
                            fields: [
                                'yccount'
                            ],
                            majorTickSteps: 1,
                            minorTickSteps: 1,
                            position: 'bottom',
                            title: '交易态势异常量',
                            decimals: 0
                        }
                    ],
                    series: [
                        {
                            type: 'column',
                            xField: 'yctype',
                            yField: 'yccount',
                            type: 'bar'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 252,
                    title: '交易态势异常地图显示'
                }
            ]
        });

        me.callParent(arguments);
    }

});