/*
 * File: app/view/TaishiPrice.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TaishiPrice', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.TaishiPrice',

    height: 499,
    width: 692,
    layout: {
        type: 'border'
    },
    title: '按交易价格分析',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    title: '交易价格趋势图',
                    items: [
                        {
                            xtype: 'chart',
                            autoRender: true,
                            height: 319,
                            width: 683,
                            animate: true,
                            insetPadding: 20,
                            store: 'TaishiPrice',
                            axes: [
                                {
                                    type: 'Category',
                                    fields: [
                                        'jysj'
                                    ],
                                    title: '交易时间',
                                    position: 'bottom'
                                },
                                {
                                    type: 'Numeric',
                                    fields: [
                                        'je'
                                    ],
                                    title: '交易价格',
                                    position: 'left'
                                }
                            ],
                            series: [
                                {
                                    type: 'line',
                                    xField: 'jysj',
                                    yField: 'je',
                                    smooth: 3
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    region: 'north',
                    height: 150,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    title: '查询条件',
                    items: [
                        {
                            xtype: 'datefield',
                            x: 10,
                            y: 20,
                            id: 'TaishiPriceDateField1',
                            width: 180,
                            fieldLabel: '起始时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'datefield',
                            x: 270,
                            y: 20,
                            id: 'TaishiPriceDateField2',
                            width: 180,
                            fieldLabel: '结束时间',
                            labelWidth: 60
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 70,
                            id: 'TaishiPriceTextField',
                            width: 180,
                            fieldLabel: '交易区域',
                            labelWidth: 60,
                            name: 'TaishiPriceTextField',
                            emptyText: '请选择区域',
                            displayField: 'name',
                            queryMode: 'local',
                            store: 'TaishiPriceCombox',
                            valueField: 'value'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var getDate1 = Ext.util.Format.date(Ext.getCmp('TaishiPriceDateField1').getValue(),'Y-m-d');
                                var getDate2 = Ext.util.Format.date(Ext.getCmp('TaishiPriceDateField2').getValue(),'Y-m-d');
                                var getKeyword = Ext.getCmp('TaishiPriceTextField').getRawValue();
                                var mystore=Ext.StoreMgr.get('TaishiPrice'); //获得store对象
                                //在load事件中添加参数
                                mystore.load(
                                {params:{
                                    searchDate1:getDate1,
                                    searchDate2:getDate2, 
                                    searchKeyword:getKeyword
                                } 
                            }
                            );
                            },
                            x: 340,
                            y: 70,
                            width: 60,
                            text: '查询'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});