/*
 * File: app/view/TaishiAlarm_Canshu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TaishiAlarm_Canshu', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.TaishiAlarm_Canshu',

    height: 500,
    width: 557,
    layout: {
        type: 'absolute'
    },
    title: '交易态势异常监测参数设置',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 50,
                    width: 240,
                    fieldLabel: '同一地区反复交易次数',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 110,
                    width: 240,
                    fieldLabel: '每亩最高交易价格',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 170,
                    width: 240,
                    fieldLabel: '每亩最低交易价格',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 230,
                    width: 240,
                    fieldLabel: '同一企业最多成交量',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 290,
                    width: 240,
                    fieldLabel: '企业失败交易次数（负信用值）上限',
                    labelWidth: 150
                },
                {
                    xtype: 'textfield',
                    x: 110,
                    y: 350,
                    width: 240,
                    fieldLabel: '举报次数',
                    labelWidth: 150
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var tabs = this.up('tabpanel');
                        tabs.removeAll(true);
                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                        var newtab = tabs.add(Ext.widget('TaishiAlarm'));
                        Ext.MessageBox.confirm('参数保存框','参数保存成功！',function(btn){
                            ;
                        });
                    },
                    x: 120,
                    y: 420,
                    width: 90,
                    text: '保存'
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var tabs = this.up('tabpanel');
                        tabs.removeAll(true);
                        //用tabs.add()新增加一个tab页面,通过Ext.widget(xtype)得到文章回收站的页面
                        var newtab = tabs.add(Ext.widget('TaishiAlarm'));

                    },
                    x: 290,
                    y: 420,
                    width: 90,
                    text: '取消'
                }
            ]
        });

        me.callParent(arguments);
    }

});