/*
 * File: app/view/z_srdagl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.z_srdagl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.ht_shjd_dagl1',

    height: 635,
    width: 943,
    layout: {
        type: 'absolute'
    },
    title: '指标申让档案管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    x: 30,
                    y: 20,
                    height: 100,
                    width: 790,
                    layout: {
                        type: 'absolute'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 20,
                            id: 'ticketid',
                            width: 180,
                            fieldLabel: '指标编号',
                            labelWidth: 60
                        },
                        {
                            xtype: 'textfield',
                            x: 240,
                            y: 20,
                            id: 'realname',
                            width: 180,
                            fieldLabel: '申请人',
                            labelWidth: 60
                        },
                        {
                            xtype: 'label',
                            x: 460,
                            y: 20,
                            height: 20,
                            text: '登记时间：'
                        },
                        {
                            xtype: 'label',
                            x: 520,
                            y: 20,
                            height: 20,
                            text: '从'
                        },
                        {
                            xtype: 'label',
                            x: 630,
                            y: 20,
                            height: 20,
                            text: '到'
                        },
                        {
                            xtype: 'datefield',
                            x: 540,
                            y: 20,
                            id: 'date1',
                            width: 90,
                            fieldLabel: 'Label',
                            hideLabel: true
                        },
                        {
                            xtype: 'datefield',
                            x: 650,
                            y: 20,
                            id: 'date2',
                            width: 90,
                            fieldLabel: 'Label',
                            hideLabel: true
                        },
                        {
                            xtype: 'radiogroup',
                            x: 30,
                            y: 70,
                            id: 'checkstate',
                            width: 200,
                            fieldLabel: '审核状态',
                            labelWidth: 60,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'checkstate',
                                    boxLabel: '通过',
                                    checked: true,
                                    inputValue: '通过'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'checkstate',
                                    boxLabel: '未通过',
                                    inputValue: '未通过'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var store=Ext.StoreMgr.get('z_zbdjsh');
                                store.load(
                                {
                                    url:'getselldagl',
                                    params:
                                    {
                                        ticketid:Ext.getCmp('ticketid').getValue(),
                                        realname:Ext.getCmp('realname').getValue(),
                                        date1:Ext.getCmp('date1').getValue(),
                                        date2:Ext.getCmp('date2').getValue(),
                                        checkstate:Ext.getCmp('checkstate').getValue()


                                    }
                                }
                                );
                            },
                            x: 650,
                            y: 70,
                            width: 90,
                            text: '查询'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    x: 30,
                    y: 150,
                    height: 320,
                    width: 790,
                    title: '指标申让档案管理',
                    titleAlign: 'center',
                    store: 'z_zbdjsh',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 68,
                            dataIndex: 'ticketid',
                            text: '指标编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 74,
                            dataIndex: 'loginname',
                            text: '登陆账号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 65,
                            dataIndex: 'realname',
                            text: '申请人'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'company',
                            text: '权属单位'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 76,
                            dataIndex: 'typelx',
                            text: '土地性质'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 75,
                            dataIndex: 'yyt',
                            text: '原用途'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 55,
                            dataIndex: 'area',
                            text: '规模'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 82,
                            dataIndex: 'address',
                            text: '位置'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 67,
                            dataIndex: 'applydate',
                            text: '申请时间',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 65,
                            dataIndex: 'checkstate',
                            text: '审核状态'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '审核通过'
                                },
                                {
                                    xtype: 'button',
                                    text: '审核不通过'
                                },
                                {
                                    xtype: 'button',
                                    width: 68,
                                    text: '删除记录'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {

                    })
                }
            ]
        });

        me.callParent(arguments);
    }

});